name: Deploy

# Trigger the workflow on push and
# pull request events on the master branch
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

    # Authenticate to the the server via ssh
    # and run our deployment script

  # security-check:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     # - name: Checkout repository
  #     #   uses: actions/checkout@v2

  #     # Empty step to pass the security-check job without any action
  #     - name: No action needed
  #       run: echo "No security checks required"

  # deploy:
  #   needs: security-check
  #   runs-on: ubuntu-latest
  #   steps:
  #     # - name: Checkout repository
  #     #   uses: actions/checkout@v2
      
  #     # Empty step to pass the deploy job without any action
  #     - name: No action needed
  #       run: echo "No deployment needed"
